services:
    php:
        build:
            context: ./build/php
        networks:
            - sail
        volumes:
            - ./:/var/www/html
            - ./build/php/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
        depends_on:
            - mysql
    grafana:
        image: 'grafana/grafana'
        ports:
            - '3000:3000'
        networks:
            - sail
        environment:
            GF_SECURITY_ADMIN_PASSWORD: '${GRAFANA_PASSWORD}'
        volumes:
            - grafana:/var/lib/grafana
    prometheus:
        image: 'prom/prometheus'
        volumes:
            - ./build/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            - sail
networks:
    sail:
        external: true
    proxy:
        external: true
volumes:
    grafana:
        driver: local
