services:
    gomaster:
        build: ./gomaster
        ports:
            - "7888:7888"
            - "8888:8888"
            - "2112:2112"
        networks:
            - sail
        restart: unless-stopped
        extra_hosts:
            -   "bb-web:192.168.1.10"
#    api:
#        build:
#            context: ./build/php
#        networks:
#            - sail
#        volumes:
#            - ./:/var/www/html
#            - ./build/php/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
#        depends_on:
#            - mysql
#            - redis
networks:
    sail:
        external: true
    proxy:
        external: true
