services:
    cron:
        build:
            context: ./build/cron
        networks:
            - sail
            - proxy
        volumes:
            - ./:/var/www/html
        extra_hosts:
            - "bb-web:192.168.1.10"
            - "bb-db:192.168.1.11"
            - "bb-master:192.168.1.12"
networks:
    sail:
        external: true
    proxy:
        external: true
